# This is a template for secrets that should be created via Azure Key Vault
# DO NOT commit actual secret values to Git
# Use Azure Key Vault CSI driver to inject secrets at runtime

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # Set this during deployment
    keyvaultName: "" # Set this during deployment
    cloudName: ""
    objects: |
      array:
        - |
          objectName: database-connection-string
          objectType: secret
          objectAlias: connection-string
        - |
          objectName: database-username
          objectType: secret
          objectAlias: username
        - |
          objectName: database-password
          objectType: secret
          objectAlias: password
        - |
          objectName: appinsights-connection-string
          objectType: secret
          objectAlias: connection-string
        - |
          objectName: keycloak-db-username
          objectType: secret
          objectAlias: db-username
        - |
          objectName: keycloak-db-password
          objectType: secret
          objectAlias: db-password
        - |
          objectName: keycloak-admin-username
          objectType: secret
          objectAlias: admin-username
        - |
          objectName: keycloak-admin-password
          objectType: secret
          objectAlias: admin-password
    tenantId: "" # Set this during deployment
  secretObjects:
  - secretName: database-secrets
    type: Opaque
    data:
    - objectName: connection-string
      key: connection-string
    - objectName: username
      key: username
    - objectName: password
      key: password
  - secretName: appinsights-secrets
    type: Opaque
    data:
    - objectName: connection-string
      key: connection-string
  - secretName: keycloak-secrets
    type: Opaque
    data:
    - objectName: db-username
      key: db-username
    - objectName: db-password
      key: db-password
    - objectName: admin-username
      key: admin-username
    - objectName: admin-password
      key: admin-password
